- app/controllers/products_controller.rb
- app/helpers/products_helper.rb
- app/models/product.rb
- config/routes.rb
- db/migrate/20161121141930_create_products.rb
- db/schema.rb
> created model and controller

- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20161121150330_add_fields_to_users.rb
- db/schema.rb
Creation des routes edit / show
Creation du controller User avec les actions edit et show
Creation des vues edit et show
ping @cedricnjanga
> added edit and show for Users

- app/models/product.rb
- app/views/products/_form.html.erb
- app/views/products/new.html.erb
creation de la view de products/new et du fichier _form.html.erb
> created view New

- app/controllers/products_controller.rb
@cedricnjanga 
open access to visitor for products (index/show)
> open access to product for visitors

- app/views/devise/sessions/new.html.erb
Mise en forme du sign_in 
@romainbousseau
> updated devise login form

- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
@cedricnjanga 
alerts in flashes partial
> moved alerts into flashes partial

- db/migrate/20161122093525_add_column_to_products.rb
- db/schema.rb
Linked product to user
@StephRob 
@cedricnjanga 
@logike95
> added user foreign key to product

- app/models/rent.rb
- db/migrate/20161122095735_create_rents.rb
- db/migrate/20161122095842_change_default_value_of_pending_to_rents.rb
- db/schema.rb
Rent model done 
@romainbousseau
> Add default value to rent status

- app/models/product.rb
- app/models/user.rb
> added has many and belong to to models

- app/controllers/rents_controller.rb
- app/helpers/rents_helper.rb
> added controller for rents

- app/controllers/rents_controller.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/unlocks/new.html.erb
> centered devise forms

- app/controllers/products_controller.rb
- app/controllers/rents_controller.rb
- app/views/rents/_form.html.erb
- app/views/rents/new.html.erb
> new and create done

- app/controllers/rents_controller.rb
- app/views/rents/show.html.erb
@cedricnjanga 
Controller:
Added Show method
Views: 
Added views
> Rents show

- app/controllers/rents_controller.rb
- config/routes.rb
Add route for validate and validate method rent controler @romainbousseau
> add validate action for rent

- app/views/shared/_nav.html.erb
Added user pic to navbar
linked your profile (navbar) to edit
> added user pic to navbar

- app/controllers/rents_controller.rb
- app/views/rents/show.html.erb
- config/routes.rb
ajout des actions validate et decline dans le controller rents et ajout des boutons dans la show @romainbousseau
> creation de actions validate et decline

- app/assets/stylesheets/components/_card.scss
- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/products/_form.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- app/views/shared/_nav.html.erb
Pics in show
Pics in Products
Pics in navbar (and replacement when no pics)
@cedricnjanga
> added pic for products

- app/views/products/show.html.erb
@cedricnjanga 
juste mis des classes sur les boutons de la show
> cleaning boutton style in the product show

- app/controllers/rents_controller.rb
- app/views/rents/show.html.erb
- config/routes.rb
@StephRob 
En fonction du statut de la commande, certains boutons sont presents : 
- si la commande est en pending => validate ou decline 
- sinon => done
> Add done button to the rent show

- app/controllers/products_controller.rb
- app/controllers/rents_controller.rb
- app/views/products/show.html.erb
- config/routes.rb
- db/migrate/20161122171706_change_defautl_value_to_availabl_cole_to_products.rb
- db/schema.rb
@romainbousseau @StephRob 
Le user qui a mis en ligne un produit peut rendre un produit non dispo
du coup ca change son statut et rend le produit non visible dans l'index (champ hidden modifié).
J'ai aussi changé dans le rents controller j'ai modifié les méthodes validate et done pour que ca change le produit : 
- si le priorio valide la loc, le produit n'est plus dispo
- si le proprio dit qu'elle est finie ca le remet en dispo
> Unavailable feature added

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_index.scss
- app/views/devise/shared/_links.html.erb
Ajout de l'icone F et changement de couleur bouton sign in et creation fichier _buttons.scss dans components @cedricnjanga
> facebook button and button.scss

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_tabs.scss
- app/controllers/rents_controller.rb
- app/views/rents/show.html.erb
- app/views/users/dashboard.html.erb
- config/routes.rb
Validation added to dashboard
Avalaible ne marche pas!!!
@cedricnjanga
> added validation to dashboard

- app/assets/javascripts/datepicker.js
- app/views/pages/home.html.erb
- app/views/products/index.html.erb
@StephRob @romainbousseau @logike95 
Formulaire date picker bon, quand on voudra prendre en compte la notion de date on pourra s'en servir.
> datepicker

- app/views/products/index.html.erb
- app/views/users/dashboard.html.erb
Added user name in products card (index)
Added name to dashboard card
> added infos

- app/controllers/users_controller.rb
- app/views/users/dashboard.html.erb
J'ai mis des  commentaires dans le user controller pour expliquer ma démarche.
@romainbousseau @StephRob @logike95
> user controller changed to resolve dashboard issue

- app/controllers/products_controller.rb
Pb réglé, j'ai mis des comms pour expliquer le tout.
> Solve issue with rent a item button

- app/controllers/products_controller.rb
Il y a plus les articles du current_user sur l'index 
@StephRob @logike95 @romainbousseau
> No more current_user products on the index

- app/controllers/products_controller.rb
- app/views/users/dashboard.html.erb
- config/routes.rb
Le bouton fonctionne
@romainbousseau
> dashboard set unavailable done

- app/assets/stylesheets/components/_buttons.scss
- app/views/products/show.html.erb
- app/views/shared/_nav.html.erb
-Lien add rent ds nav bar
-Stylisé les bouttons de la nav bar
-Back btn dans la show vers index
@cedricnjanga
> Add link new product

- app/controllers/products_controller.rb
- app/views/pages/home.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- app/views/rents/_new.html.erb
@StephRob @logike95 @romainbousseau 
Pb fb réglé 
J'ai aussi commencé à m'occuper des dates : 
- quand on fait une recherche dans la home, formulaire de de l'index est pré-rempli avec les valeurs de de recherche
- par contre je n'arrive pas pour le moment à passer les variables de dates (stras_date, end_date) dans le formulaire de la new rent pour qu'il soit pré-rempli avec les bonnes dates
> Facebook validate pb

- app/assets/stylesheets/components/_datepicker.scss
- app/assets/stylesheets/components/_index.scss
resize du drop-down menu et ajout du stylesheet component _datepicker.scss @romainbousseau
> resize dropdown-menu

- app/assets/stylesheets/layout/_footer2.scss
- app/views/layouts/application.html.erb
changement du title "TODO" en "GduTosma" et la couleur de suppot mail dans le footer @cedricnjanga
> update title and support color

- app/assets/stylesheets/pages/_home.scss
- app/helpers/users_helper.rb
- app/views/products/show.html.erb
- app/views/rents/_new.html.erb
> Rent issue
